<?php

namespace NewsletterBundle\Repository;

/**
 * InscriNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
