<?php

namespace NewsletterBundle\Repository;

/**
 * NewsletterWRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterWRepository extends \Doctrine\ORM\EntityRepository
{
    public function setDateEnvoi($id)
    {
        $q=$this->getEntityManager()->createQuery(
            "update NewsletterBundle:NewsletterW nw set nw.dateEnvoi=CURRENT_TIMESTAMP() where nw.id=$id"
        );
        $q->execute();
    }
    public function getPaysInscri()
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql="SELECT DISTINCT(pays) as p FROM inscri_news ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    public function getMailPaysInscri($pays)
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql="SELECT a_mail as m FROM `inscri_news` WHERE  UPPER(pays)=UPPER('".$pays."')";
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    public function getMailInscri()
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql="SELECT a_mail as m FROM `inscri_news`";
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
