<?php

namespace NewsletterBundle\Repository;

/**
 * NewsletterWRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterWRepository extends \Doctrine\ORM\EntityRepository
{
    public function setDateEnvoi($id)
    {
        $q=$this->getEntityManager()->createQuery(
            "update NewsletterBundle:NewsletterW nw set nw.dateEnvoi=CURRENT_TIMESTAMP() where nw.id=$id"
        );
        $q->execute();
    }
}
