<?php

namespace NewsletterBundle\Repository;

/**
 * NewsHTMLBuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsHTMLBuilderRepository extends \Doctrine\ORM\EntityRepository
{

}
