<?php

namespace AideBundle\Repository;

/**
 * CategorieAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieAideRepository extends \Doctrine\ORM\EntityRepository
{
}
