<?php

namespace AideBundle\Repository;

/**
 * CommentaireAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireAideRepository extends \Doctrine\ORM\EntityRepository
{
}
