<?php

namespace AideBundle\Repository;

/**
 * DemandeAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAideRepository extends \Doctrine\ORM\EntityRepository
{
}
