<?php

namespace AideBundle\Repository;

/**
 * ParticipationAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationAideRepository extends \Doctrine\ORM\EntityRepository
{
}
