<?php

namespace AideBundle\Repository;

/**
 * ReactionAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionAideRepository extends \Doctrine\ORM\EntityRepository
{

    //retourne nombre de reaction totale pour une demande
    public function nbReactParDmnd($idDmnd){

        $query = $this->createQueryBuilder('r')
            ->where('r.idDemande = :iddmnd')
            ->setParameters(array(
                'iddmnd'=>$idDmnd,
            ))
            ->select('count(r.id)')
            ->getQuery();


        return $query->getSingleScalarResult();

    }

}
