<?php

namespace AideBundle\Repository;

/**
 * ReactionAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionAideRepository extends \Doctrine\ORM\EntityRepository
{
}
