<?php

namespace AideBundle\Repository;

/**
 * SignalementAideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementAideRepository extends \Doctrine\ORM\EntityRepository
{
}
