publicationdon_index:
    path:     /
    defaults: { _controller: "RestoOrgBundle:PublicationDon:index" }
    methods:  GET

publicationdon_show:
    path:     /{id}/show
    defaults: { _controller: "RestoOrgBundle:PublicationDon:show" }
    methods:  GET

publicationdon_new:
    path:     /new
    defaults: { _controller: "RestoOrgBundle:PublicationDon:new" }
    methods:  [GET, POST]

publicationdon_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestoOrgBundle:PublicationDon:edit" }
    methods:  [GET, POST]

publicationdon_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestoOrgBundle:PublicationDon:delete" }
    methods:  DELETE
rec_test:
    path:     /rec
    defaults: { _controller: "RestoOrgBundle:PublicationDon:rec" }
    methods:  GET
after_request:
    path:     /afterRequest
    defaults: { _controller: "RestoOrgBundle:PublicationDon:afterRequest" }
after_request_update:
    path:     /afterRequestUpdate
    defaults: { _controller: "RestoOrgBundle:PublicationDon:afterRequestUpdate" }
after_requestIP:
    path:     /afterRequestIP
    defaults: { _controller: "RestoOrgBundle:PublicationDon:afterRequestIP" }
api_get_all:
    path:     /getAllApi
    defaults: { _controller: "RestoOrgBundle:PublicationDon:getAllApi" }
api_add_publication:
    path:     /addPublicationApi
    defaults: { _controller: "RestoOrgBundle:PublicationDon:addPublicationApi" }
api_edit_publication:
    path:     /editPublicationApi
    defaults: { _controller: "RestoOrgBundle:PublicationDon:editPublicationApi" }
api_delete_publication:
    path:     /deletePublicationApi
    defaults: { _controller: "RestoOrgBundle:PublicationDon:deletePublicationApi" }
api_rec:
    path:     /recApi
    defaults: { _controller: "RestoOrgBundle:PublicationDon:recApi" }

