<?php

namespace RestoDonBundle\Repository;

/**
 * DonRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
