<?php

namespace RestoDonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DonRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRestaurantRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllDONATORNAME($userName) {

        return $this->getEntityManager()
            ->createQuery(
            'SELECT id
    FROM UserBundle:User id
    WHERE id.username = :username'
        )->setParameter('username', $userName)
            -> getResult();

}

}
