<?php

namespace RestoDonBundle\Repository;

/**
 * RepasServiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasServiRepository extends \Doctrine\ORM\EntityRepository
{
}
