<?php

namespace RestoDonBundle\Repository;

/**
 * TarifRestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRestoRepository extends \Doctrine\ORM\EntityRepository
{
}
