imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@haytBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@NewsletterBundle/Resources/config/services.yml" }
    - { resource: "@RestoDonBundle/Resources/config/services.yml" }
    - { resource: "@AideBundle/Resources/config/services.yml" }
    - { resource: "@RestoOrgBundle/Resources/config/services.yml" }
    - { resource: "@CagnotteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      '%mailer_host%'
    port:   25
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    spool: {type: memory}

sensio_framework_extra:
   router:
        annotations: false

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "amine.gongi@esprit.tn"
        sender_name: "DoNation_no_reply"
    registration:
        confirmation:
            enabled: true

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'


endroid_qr_code:
    writer: 'png'
    size: 300
    margin: 30
    foreground_color: { r: 255, g: 255, b: 255 }
    background_color: { r: 9, g: 152, b: 124 }
    error_correction_level: low # low, medium, quartile or high
    encoding: UTF-8
    label: Donation
    label_font_size: 30
    label_alignment: center # left, center or right
    label_margin: { b: 20 , t: 20 }
    logo_width: 150
    logo_height: 200
    validate_result: false # checks if the result is readable
    writer_options:
        exclude_xml_declaration: true