cagnotte:
    resource: "@CagnotteBundle/Resources/config/routing.yml"
    prefix:   /Cagnotte

resto_org:
    resource: "@RestoOrgBundle/Resources/config/routing/publicationdon.yml"
    prefix:   /RestoOrg
aide:
    resource: "@AideBundle/Resources/config/routing.yml"
    prefix:   /aide

resto_don:
    resource: "@RestoDonBundle/Resources/config/routing.yml"
    prefix:   /RestoDon

pub:
    resource: "@PubBundle/Resources/config/routing/pub.yml"
    prefix:   /admin/pub

newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /admin/Newsletter

newsletterF:
    resource: "@NewsletterBundle/Resources/config/routingF.yml"
    prefix:   /News

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /admin/user

userFront:
    resource: "@UserBundle/Resources/config/routingF.yml"
    prefix:   /user

hayt:
    resource: "@haytBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /app

endroid_qr_code:
    resource: "@EndroidQrCodeBundle/Resources/config/routes.yaml"
    prefix: /qr-code