user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

hayt:
    resource: "@haytBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
