<?php

namespace CagnotteBundle\Repository;

/**
 * cagnotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cagnotteRepository extends \Doctrine\ORM\EntityRepository
{
}
