<?php

namespace CagnotteBundle\Repository;

/**
 * categoriecagnotteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriecagnotteRepository extends \Doctrine\ORM\EntityRepository
{
}
