<?php

namespace CagnotteBundle\Repository;

/**
 * donationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class donationsRepository extends \Doctrine\ORM\EntityRepository
{
}
