<?php

namespace EmploiBundle\Repository;

/**
 * CategorieEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEmploiRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIdTitre($titre)
    {
        $conn = $this->getEntityManager()
                     ->getConnection();
        $sql="SELECT id FROM categorie_emploi WHERE titre_categorie ='$titre' ";
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
