<?php

namespace EmploiBundle\Repository;

/**
 * EmploisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploisRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechFiltre($rech , $te,$co , $cate , $oo)
    {
        $query = $this->createQueryBuilder('q');
        if(!empty($rech)){
            $query->where("q.titre like '%$rech%'")
                ->orWhere("q.description like '%$rech%'")
                ->orWhere("q.salaire like '%$rech%'")
                ->orWhere("q.typeDemploi like '%$rech%'")
                ->orWhere("q.typeContrat like '%$rech%'");
        }
        $i=0;
        if(!empty($te)){
            foreach ($te as $t) {
                if($i == 0){
                    $query->andWhere("q.typeDemploi like '$t'");
                    $i++;
                }
                else
                    $query->orWhere("q.typeDemploi like '$t'");
            }
        }

        $i=0;
        if(!empty($co)) {
            foreach ($co as $te) {
                if($i == 0){
                    $query->andWhere("q.typeContrat like '$te'");
                    $i++;
                }
                else
                    $query->orWhere("q.typeContrat like '$te'");
            }
        }
        $i=0;
        if(!empty($cate)){
            foreach ($cate as $categorie) {
                if($i == 0){
                    $query->andWhere("q.idcategorie = '$categorie'");
                    $i++;
                }
                else
                    $query->orWhere("q.idcategorie = '$categorie'");
            }
        }

        if(!empty($oo)){
            $query->orderBy('q.id',$oo);
        }

        return $query->getQuery()
            ->getResult();

    }
}
