<?php

namespace UserBundle\Repository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSender($rec)
    {
        $q=$this->getEntityManager()->createQuery(
            "Select distinct(c.sender) from UserBundle:Conversation c where c.receiver='$rec' "
        );
        return $q->getResult();
    }

    public function getReceiver($rec)
    {
        $q=$this->getEntityManager()->createQuery(
            "Select distinct(c.receiver) from UserBundle:Conversation c where c.receiver!='$rec'"
        );
        return $q->getResult();
    }

    public function getConversation($rec)
    {
        $q=$this->getEntityManager()->createQuery(
            "Select c from UserBundle:Conversation c where c.receiver='$rec'"
        );
        return $q->getResult();
    }

    public function getSRConversation($rec,$sen)
    {
        $q=$this->getEntityManager()->createQuery(
            "Select c from UserBundle:Conversation c where (c.receiver='$rec' and c.sender='$sen') or (c.receiver='$sen' and c.sender='$rec')"
        );
        return $q->getResult();
    }

    public function getInContact($re)
    {
        $rec= $this->getReceiver($re);
        $sen = $this->getSender($re);

        $ic[] = array_merge($sen, $rec);
        $ii = array_unique($ic);

        return $sen;
    }


}
