cagnotte_homepage:
    path:     /
    defaults: { _controller: CagnotteBundle:cagnotte:index }

cagnotte_new:
    path:     /new
    defaults: { _controller: CagnotteBundle:cagnotte:new }

cagnotte_edit:
    path:     /edit/{id}
    defaults: { _controller: CagnotteBundle:cagnotte:edit }

cagnotte_delete:
    path:     /delete/{id}
    defaults: { _controller: CagnotteBundle:cagnotte:delete }

cagnotte_show:
    path:     /show/{id}
    defaults: { _controller: CagnotteBundle:cagnotte:show }

cagnotte_donate:
    path:     /{id}/donate
    defaults: { _controller: CagnotteBundle:cagnotte:donate }

cagnotte_charge:
    path:     /{id}/charge
    defaults: { _controller: CagnotteBundle:cagnotte:charge }

cagnotte_take:
    path:     /{id}/take
    defaults: { _controller: CagnotteBundle:cagnotte:take }

cagnotte_new_mobile:
    path:     /newCagnotteMobile
    defaults: { _controller: CagnotteBundle:cagnotteMobile:new }
    methods: [GET, POST]