newsletter_homepage:
    path:     /
    defaults: { _controller: NewsletterBundle:Default:index }

newsletterHTMLBuilder:
    path:     /NHB
    defaults: { _controller: NewsletterBundle:NewsletterHTMLBuilder:NBH }

newsletterHTMLBuilder_delete:
    path:     /{id}/NHBDel
    defaults: { _controller: NewsletterBundle:NewsletterHTMLBuilder:delete }
