newsletter_homepage:
    path:     /
    defaults: { _controller: NewsletterBundle:Default:index }

newsletterHTMLBuilder:
    path:     /NHB
    defaults: { _controller: NewsletterBundle:NewsletterHTMLBuilder:NBH }

newsletterHTMLBuilder_delete:
    path:     /{id}/NHBDel
    defaults: { _controller: NewsletterBundle:NewsletterHTMLBuilder:delete }

ne:
    path:     /n
    defaults: { _controller: NewsletterBundle:NewsletterHTMLBuilder:nn }

newsletterW:
    path:     /NW
    defaults: { _controller: NewsletterBundle:Newsletter:news }

newsletterInscri:
    path:     /NI
    defaults: { _controller: NewsletterBundle:NewsletterInscri:newsInscri }
