user_profil:
    path:     /profil
    defaults: { _controller: UserBundle:Default:show }

user_smsSend:
    path:     /smsSend
    defaults: { _controller: UserBundle:Default:smsSend }

UserAutreProfil:
    path:     /profil/{id}
    defaults: { _controller: UserBundle:Default:showOUser }

send_add_message:
    path:     /send_msg
    defaults: { _controller: UserBundle:Conversation:send_add }

get_convs:
    path:     /get_convs
    defaults: { _controller: UserBundle:Conversation:getConvs }

list_convs:
    path:     /list_convs
    defaults: { _controller: UserBundle:Conversation:getlistConv }

mob_getUserID:
    path:     /api/getUserID
    defaults: { _controller: UserBundle:UserMob:getUserId }

mob_getUserMail:
    path:     /api/getUserMail
    defaults: { _controller: UserBundle:UserMob:getUserMail }

mob_login:
    path:     /api/login
    defaults: { _controller: UserBundle:UserMob:login }

mob_activer:
    path:     /api/activer
    defaults: { _controller: UserBundle:UserMob:activerCompte }

mob_inscri:
    path:     /api/inscri
    defaults: { _controller: UserBundle:UserMob:Inscription }

mob_token:
    path:     /api/tokenMail
    defaults: { _controller: UserBundle:UserMob:getTokenByMail }

mob_ModUs:
    path:     /api/modus
    defaults: { _controller: UserBundle:UserMob:ModifierCompteUS }

