<?php

namespace RestoOrgBundle\Repository;

/**
 * PublicationDonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationDonRepository extends \Doctrine\ORM\EntityRepository
{
}
