demandeaide_index:
    path:     /
    defaults: { _controller: "AideBundle:DemandeAide:index" }
    methods:  GET


demandeaide_indexbycat:
    path:     /demandespour/{id}
    defaults: { _controller: "AideBundle:DemandeAide:findAllForOneCat" }
    methods:  GET

demandeaide_show:
    path:     /{id}/show
    defaults: { _controller: "AideBundle:DemandeAide:show" }
    methods:  GET

demandeaide_new:
    path:     /new
    defaults: { _controller: "AideBundle:DemandeAide:new" }
    methods:  [GET, POST]

demandeaide_edit:
    path:     /{id}/edit
    defaults: { _controller: "AideBundle:DemandeAide:edit" }
    methods:  [GET, POST]

demandeaide_delete:
    path:     /{id}/delete
    defaults: { _controller: "AideBundle:DemandeAide:delete" }
    methods:  DELETE

demandeaide_all:
    path:     /all
    defaults: { _controller: "AideBundle:DemandeAideMobile:index" }
    methods:  GET

demandeaide_find:
    path:     /find/{id}
    defaults: { _controller: "AideBundle:DemandeAideMobile:find" }
    methods:  GET


demandeaide_findallforonecat:
    path:     /findallforonecat/{id}
    defaults: { _controller: "AideBundle:DemandeAideMobile:findAllForOneCat" }
    methods:  GET


demandeaide_add:
    path:     /add
    defaults: { _controller: "AideBundle:DemandeAideMobile:add" }
    methods:  [GET, POST]
