participationaide_index:
    path:     /
    defaults: { _controller: "AideBundle:ParticipationAide:index" }
    methods:  GET

participationaide_show:
    path:     /{id}/show
    defaults: { _controller: "AideBundle:ParticipationAide:show" }
    methods:  GET

participationaide_new:
    path:     /{id}/new
    defaults: { _controller: "AideBundle:ParticipationAide:new" }
    methods:  [GET, POST]

participationaide_edit:
    path:     /{id}/edit
    defaults: { _controller: "AideBundle:ParticipationAide:edit" }
    methods:  [GET, POST]

participationaide_delete:
    path:     /{id}/delete
    defaults: { _controller: "AideBundle:ParticipationAide:delete" }
    methods:  DELETE


participationaide_all:
    path:     /all
    defaults: { _controller: "AideBundle:ParticipationAideMobile:index" }
    methods:  GET

#Return all participations for a specific demande
participationaide_find:
    path:     /find/{id}
    defaults: { _controller: "AideBundle:ParticipationAideMobile:findAllForOne" }
    methods:  GET


participationaide_add:
    path:     /add
    defaults: { _controller: "AideBundle:ParticipationAideMobile:add" }
    methods:  [GET, POST]


participationaide_remove:
    path:     /delete
    defaults: { _controller: "AideBundle:ParticipationAideMobile:delete" }
    methods:  [GET, POST]
