reactionaide_index:
    path:     /
    defaults: { _controller: "AideBundle:ReactionAide:index" }
    methods:  GET

reactionaide_show:
    path:     /{id}/show
    defaults: { _controller: "AideBundle:ReactionAide:show" }
    methods:  GET

reactionaide_new:
    path:     /new
    defaults: { _controller: "AideBundle:ReactionAide:new" }
    methods:  [GET, POST]

reactionaide_edit:
    path:     /{id}/edit
    defaults: { _controller: "AideBundle:ReactionAide:edit" }
    methods:  [GET, POST]

reactionaide_delete:
    path:     /{id}/delete
    defaults: { _controller: "AideBundle:ReactionAide:delete" }
    methods:  DELETE
