<?php

namespace PubBundle\Repository;

/**
 * Apps_countriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Apps_countriesRepository extends \Doctrine\ORM\EntityRepository
{
}
