<?php

namespace PubBundle\Repository;

/**
 * Publicite_countryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Publicite_countryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPubsStat($i)
    {
        $q=$this->getEntityManager()->createQuery("Select f from PubBundle:Publicite_country f where f.idPublicite='$i' ");
        var_dump($q->getSQL());
        return $q->getResult();
    }

    public function getPubsStats($i)
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql="select country_code , nbrClick from apps_countries INNER JOIN publicite_country on publicite_country.idCountry=apps_countries.id WHERE publicite_country.idPublicite =:ii ";
        $stmt = $conn->prepare($sql);
        $stmt->execute(array('ii' => $i));

        return $stmt->fetchAll();
    }
}
