<?php

namespace PubBundle\Repository;

/**
 * PubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubRepository extends \Doctrine\ORM\EntityRepository
{
    public  function randomPub()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql="select * from Publicite order by rand() limit 1 ";
        $stmt = $conn->prepare($sql);

        return $stmt->fetchAll();
    }
}
