<?php

namespace PubBundle\Repository;

/**
 * PubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubRepository extends \Doctrine\ORM\EntityRepository
{
}
