tarifresto_index:
    path:     /
    defaults: { _controller: "RestoDonBundle:TarifResto:index" }
    methods:  GET

tarifresto_show:
    path:     /{idTarif}/show
    defaults: { _controller: "RestoDonBundle:TarifResto:show" }
    methods:  GET

tarifresto_new:
    path:     /new
    defaults: { _controller: "RestoDonBundle:TarifResto:new" }
    methods:  [GET, POST]

tarifresto_edit:
    path:     /{idTarif}/edit
    defaults: { _controller: "RestoDonBundle:TarifResto:edit" }
    methods:  [GET, POST]

tarifresto_delete:
    path:     /{idTarif}/delete
    defaults: { _controller: "RestoDonBundle:TarifResto:delete" }
    methods:  DELETE
