resto_don_tarifresto:
    resource: "@RestoDonBundle/Resources/config/routing/tarifresto.yml"
    prefix:   /tarifresto

resto_don_repasservi:
    resource: "@RestoDonBundle/Resources/config/routing/repasservi.yml"
    prefix:   /repasservi

resto_don_donrestaurant:
    resource: "@RestoDonBundle/Resources/config/routing/donrestaurant.yml"
    prefix:   /donrestaurant

resto_don_homepage:
    path:     /
    defaults: { _controller: RestoDonBundle:Default:index }

jsonRestaurant:
    path: /ListMapResto
    defaults: { _controller: RestoDonBundle:Default:jsonRestaurant }

newDonmobile:
    path:     /newDonMobile
    defaults: { _controller: "RestoDonBundle:DonRestaurantMobile:new" }
    methods: [GET, POST]

newRepasmobile:
    path:     /newRepasMobile
    defaults: { _controller: "RestoDonBundle:RepasServiMobile:new" }
    methods: [GET, POST]

getTarifmobile:
    path:     /getTarifMobile
    defaults: { _controller: "RestoDonBundle:TarifRestoMobile:get" }
    methods: [GET, POST]

newTarifmobile:
    path:     /newTarifMobile
    defaults: { _controller: "RestoDonBundle:TarifRestoMobile:new" }
    methods: GET