resto_don_tarifresto:
    resource: "@RestoDonBundle/Resources/config/routing/tarifresto.yml"
    prefix:   /tarifresto

resto_don_repasservi:
    resource: "@RestoDonBundle/Resources/config/routing/repasservi.yml"
    prefix:   /repasservi

resto_don_donrestaurant:
    resource: "@RestoDonBundle/Resources/config/routing/donrestaurant.yml"
    prefix:   /donrestaurant

resto_don_homepage:
    path:     /
    defaults: { _controller: RestoDonBundle:Default:index }

resto_don_backpage:
    path:     /back
    defaults: { _controller: RestoDonBundle:Default:index }

resto_don_donate_page:
    path:     /DonatePage
    defaults: { _controller: RestoDonBundle:Default:donatePage }

resto_don_donate:
    path:     /Donate/{montant}
    defaults: { _controller: RestoDonBundle:Default:donate }

jsonRestaurant:
    path: /ListMapResto
    defaults: { _controller: RestoDonBundle:Default:jsonRestaurant }

jsonRestaurantMobile:
    path: /ListMapRestoMobile
    defaults: { _controller: RestoDonBundle:Default:jsonRestaurantMobile }

newDonmobile:
    path:     /newDonMobile
    defaults: { _controller: "RestoDonBundle:DonRestaurantMobile:new" }
    methods: [GET, POST]

listDonmobile:
    path:     /listDonMobile
    defaults: { _controller: "RestoDonBundle:DonRestaurantMobile:listDon" }
    methods: [GET, POST]

newRepasmobile:
    path:     /newRepasMobile
    defaults: { _controller: "RestoDonBundle:RepasServiMobile:new" }
    methods: [GET, POST]

listRepasMobile:
    path:     /listRepasMobile
    defaults: { _controller: "RestoDonBundle:RepasServiMobile:listRepasMobile" }
    methods: [GET, POST]

deleteRepasmobile:
    path:     /deleteRepasMobile
    defaults: { _controller: "RestoDonBundle:RepasServiMobile:deleteRepasMobile" }
    methods: [GET, POST]

getTarifmobile:
    path:     /getTarifMobile
    defaults: { _controller: "RestoDonBundle:TarifRestoMobile:get" }
    methods: [GET, POST]

newTarifmobile:
    path:     /newTarifMobile
    defaults: { _controller: "RestoDonBundle:TarifRestoMobile:new" }
    methods: [GET, POST]

mobileMapAllResto:
    path:     /mobileMapAllResto
    defaults: { _controller: "RestoDonBundle:Default:mobileMap" }
    methods: [GET, POST]